#!/bin/sh

## error handling
no_install='FLAPW WAS NOT INSTALLED'

## check update
if [ ! -e 'flapw.tar.gz' ]; then
  echo 'Warning: There is no flapw.tar.gz'
  #echo $no_install
  #exit
fi

## platform
plat='debug user gfortran ifort windows macos ncm genkai ohtaka'
echo 'Platform'
echo '  debug:    debug-linux with ifort+mkl'
echo '  user:     user-linux'
echo '  gfortran: linux with gfortran+openblas'
echo '  ifort:    lunux with ifort+mkl'
echo '  windows:  conda-windows with gfortran+openblas'
echo '  macos:    conda-macOS with gfortran+openblas'
echo '  ncm:      ncm-linux wiht ifort+mkl'
echo '  genkai:   genkai-linux with ifort+mkl'
echo '  ohtaka:   ohtaka-linux with ifort+mkl'
echo -n 'Which platform? '
read platform
platok='n'
for platchk in $plat; do
  if [ "$platchk" = "$platform" ]; then
    platok='y'
    echo "Install on platform $platform"
  fi
done
if [ "$platok" != 'y' ]; then
  echo 'Platform is not found'
  echo "$no_install"
  exit
fi

## home directory
if [ "$platform" = 'windows' ] ; then
  homedir="$USERPROFILE"
else
  homedir="$HOME"
fi

## User mode
if [ "$platform" = 'user' ]; then
  echo 'Edit MAKEFILES/make.conf'
fi

#MPI
mpi='n'
echo -n 'Parallel with MPI? (y/n) '
read mpi
if [ "$mpi" = 'y' ]; then
  if [ "$platform" = 'windows' ]; then
    echo "MPI is not supported on $platform"
    echo "$no_install"
    exit
  fi
  if [ "$platform" = 'macos' ]; then
    echo "MPI is not supported on $platform"
    echo "$no_install"
    exit
  fi
  if [ "$platform" = 'gfortran' ]; then
    echo "MPI is not supported on $platform"
    echo "$no_install"
    exit
  fi
fi

## readme files
readme='README.flapw'

## source files
source='MAIN VER KPTS DEN POT DOS EFG MIX FORCE TOOLS SYM LMATRX PMATRX SOC LDA GGA NCM U FCONST ELPH PLOT HSMATRX BASE STDEN ATOM FERMI TENERGY INPUT FFT STAR LHARM FLIB LHARMOLD NEB VDW MDPLS'

## modules files
modi='MODI/kinds.o'
modi="$modi MODI/mod_lapack.o MODI/mod_diag.o"
modi="$modi MODI/mod_parameters.o MODI/mod_cfg.o MODI/mod_eps.o MODI/mod_constants.o"
modi="$modi MODI/mod_matsplit.o MODI/mod_matarray.o"
source="MODS MODW $source"

## other files
others='TIMING MAKEFILES postCAL postMU bin shell DEMO SED'

## modules for mpi
if [ "$mpi" = 'y' ]; then
  modi="$modi MODI/mod_mpifnc.o MODI/mod_bcd.o MODI/mod_pdiag.o"
fi

## check readme files
if [ ! -e "$readme" ]; then
  echo "There is no $readme"
  echo "$no_install"
  exit
fi

## chech old files
if [ "$platform" != 'debug' ]; then
  file_old='n'
  for dir in $source $others MODI; do
    if [ -d "$dir" ]; then
      file_old='y'
      #echo 'Warning: There are old files'
      #echo "$no_install"
      #exit
    fi
  done
  if [ "$file_old" = 'y' ]; then
    echo 'Warning: There are old files'
  fi
fi

## setting
cur_dir=`pwd`
out='makefile'
if [ "$mpi" = 'y' ]; then
  progname='pflapw'
else
  progname='flapw'
fi

## path for include files
INC='$(IPATH)../MODI $(IPATH)../MODS $(IPATH)../MODW'

## install file
source_gz='flapw.tar.gz'
source_tar='flapw.tar'
if [ -e "$source_gz" ]; then
  gzip -d "$source_gz"
fi

## install start ##
if [ -e "$source_tar" ]; then
  echo -n 'Do you want to install? (y/n) '
  read response
  if [ "$response" != 'y' ]; then
    echo "$no_install"
    exit
  fi
  rm -fr 'flapw' 'pflapw'
  for dir in $source $others MODI; do
    tar xf "$source_tar" "$dir"
  done
else
  echo 'Installation file is not found'
  echo "$no_install"
  exit
fi

##  set makefile
if [ "$mpi" = 'y' ]; then
  platmake="$platform"'_mpi'
else
  platmake="$platform"
fi
if [ -e "MAKEFILES/make.conf_$platmake" ]; then
  cp -f "MAKEFILES/make.conf_$platmake" 'MAKEFILES/make.conf'
else
  echo 'Makefile is not found'
  echo "$no_install"
  exit
fi

##  creat makefile
rm -f "$out"
rm -f "$progname"
echo 'include MAKEFILES/make.conf' > "$out"
echo ' ' >> "$out"
echo '.SUFFIXES:' >> "$out"
echo '.SUFFIXES: .o .f90 .f' >> "$out"
echo ' ' >> "$out"
echo 'SHELL=/bin/sh' >> "$out"
echo "PROGRAM=$progname" >> "$out"
echo ' ' >> "$out"

list=""
listp=""
list_para=""
for directory in $source; do
  if [ -d "$directory" ]; then
    cd "$directory"
    filelist=`ls -1 *.f`
    for file in $filelist; do
      list="$list $directory/${file%.*}.o"
      listp="$listp $directory/$file"
    done
  else
    echo "Directory $directory is not found"
    echo "$no_install"
    exit
  fi
  cd $cur_dir
done
list_para="$list_para `grep -l "include 'para" $listp`"
listp=""
for file in $list_para; do
  listp="$listp ${file%.*}.o"
done

i=0
set -- $modi ; line_num=$#
line=""
for file in $modi; do
  i=$(( i+1 ))
  line="$line $file"
  if [ $(( i % 4 )) -eq 0 ] || [ $i -eq $line_num ]; then
    if [ $i -eq 4 ]; then
      echo "MODI =$line"'\' >> "$out"
    elif [ $i -eq $line_num ]; then
      echo "      $line" >> "$out"
    else
      echo "      $line"'\' >> "$out"
    fi
    line=""
  fi
done
echo ' '>> "$out"

if [ -e "TIMING/time_$platform.f" ]; then
  cp -f "TIMING/time_$platform.f" 'TIMING/get_second.f'
else
  echo 'Etime file is not found'
  echo "$no_install"
  exit
fi
echo 'TIME = TIMING/get_second.o' >> "$out"
echo ' ' >> "$out"

i=0
set -- $list ; line_num=$#
line=""
for file in $list; do
  i=$(( i+1 ))
  line="$line $file"
  if [ $(( i % 4 )) -eq 0 ] || [ $i -eq $line_num ]; then
    if [ $i -eq 4 ]; then
      echo "OBJS =$line"'\' >> "$out"
    elif [ $i -eq $line_num ]; then
      echo "      $line" >> "$out"
    else
      echo "      $line"'\' >> "$out"
    fi
    line=""
  fi
done
echo ' '>> "$out"

echo '.f.o:' >> "$out"
echo '		cd $(@D);$(CF) $(FFLAGS) '"$INC"' -c $(<F)' >> "$out"
echo ' ' >> "$out"

echo '.f90.o:' >> "$out"
echo '		cd $(@D);$(CF) $(FFLAGS) '"$INC"' -c $(<F)' >> "$out"
echo ' ' >> "$out"

echo 'main:     $(PROGRAM)' >> "$out"
echo ' ' >> "$out"

echo '$(PROGRAM):	$(MODI) $(OBJS) $(TIME)' >> "$out"
echo '		$(CF) $(LDFLAGS) -o $(PROGRAM) $(MODI) $(OBJS) $(TIME) $(LIBS)' >> "$out"
echo ' ' >> "$out"

echo 'clean:' >> "$out"
echo '		-rm -f $(MODI) $(OBJS) $(TIME) $(PROGRAM) */*.mod */*_genmod.f90 postCAL/post*/*.o postCAL/post*/x* postCAL/post*/*.mod postCAL/post*/*_genmod.f90' >> "$out"
echo ' ' >> "$out"

## updata bin files
flbin='n'
echo -n 'Do you want to update FL-commands? (y/n) '
read flbin
if [ "$flbin" = 'y' ]; then
  bindir="$homedir/FLAPW"
  if [ ! -d "$bindir" ]; then
    mkdir "$bindir"
  fi
  bindir="$homedir/FLAPW/bin"
  if [ ! -d "$bindir" ]; then
    mkdir "$bindir"
  else
    if [ ! -d "$bindir/old" ]; then
      mkdir "$bindir/old"
    fi
    for f in "$bindir"/FL*;do
      if [ -e "$f" ]; then
        mv -f "$f" "$bindir/old/"
      fi
    done
  fi
  for f in 'bin'/FL*;do
    if [ -e "$f" ]; then
      cp -f "$f" "$bindir/"
    fi
  done
fi

## add hostname
ver_dir="$cur_dir/VER"
host_add="$HOSTNAME"
vers_add=`head -1 $readme | awk '{print $2}'`
if [ -e "$ver_dir/version.f" ]; then
  rm -f "$ver_dir/version.f"
fi
sed -e "s/SRC_HOST/$host_add/g" "$ver_dir/version" | sed -e "s/SRC_VERS/$vers_add/g"  > "$ver_dir/version.f"

## print registration
rgst=`grep 'cha_rgst=' VER/register.f | head -1 | sed 's/cha_rgst=//g' | awk '{print $1}'`
echo "The code is registered in $rgst"

## completed
echo 'FLAPW was successfully installed'
exit
